backend:
  name: git-gateway # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: concerts
    label: 'Konzerte'
    folder: 'content'
    create: true
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}.md'
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Stadt', name: 'city', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Vorschaubild', name: 'cover', widget: 'image', hint: 'Für die Liste und als Player-Hintergrund' }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'Gewünschte Webadresse ohne "https://nitrox.tv" vorne dran. Z.B. "crucified-barbara-muenchen-garage"',
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - label: 'Videos'
        name: 'videos'
        collapsed: false
        widget: 'list'
        fields:
          - { label: Name, name: name, widget: string }
          - { label: URL, name: src, widget: string, hint: 'https://drive.google.com/uc?export=download&id=💥FILE_ID' }
      - { label: 'Text', name: 'body', widget: 'markdown', hint: 'Text des Konzert-Artikels' }
