backend:
  name: git-gateway # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: 'Post'
    folder: 'content'
    create: true
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}.md'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'City', name: 'city', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Cover Image', name: 'cover', widget: 'image' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - label: 'Videos'
        name: 'videos'
        collapsed: true
        widget: 'list'
        fields:
          - { label: Name, name: name, widget: string }
          - { label: URL, name: src, widget: string }
      - { label: 'Body', name: 'body', widget: 'markdown' }
